### ISSUE TITLE
Unclear on how to use it in Node.js

### ISSUE THREAD

**Issue by smileservices** [w3core/min.css#1]
Thanks for the work done with the script. However, for someone new to Node.js and npm scripts, I can't make use of your documentation for working with Node.js. What the output of mincss(input) is just the name of the files.

**Comment by w3core** [comment]
The `input` argument of `mincss(input)` function should be *uncompressed* CSS string. Result of function execution will *compressed* CSS string.

Working example of usage (multiple files compression) you can find [here](https://github.com/w3core/min.css/blob/master/min.css)
